language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:

    # set the environment variable CURRENT_DIR
    - CURRENT_DIR=`pwd`

    # change to the current directory
    - cd $CURRENT_DIR

    - echo $NODE_LABELS

    # rename the cloned folder
    - cd .. && cp -r $NODE_LABELS GigaSOM && cd GigaSOM

    # launch the tests
    - bash .artenolis/runtests.sh

after_success:
    - if [ "$ARCH" == "Linux" ]; then
        $ARTENOLIS_SOFT_PATH/julia/$JULIA_VER/bin/julia --color=yes -e 'using Coverage; Codecov.submit(process_folder())';
      fi

after_script:
    # clean up the build directory
    - cd .. && rm -rf GigaSOM