language: julia

os:
    - linux

julia:
    - 0.6
    - 0.7
    - 1.0
    - nightly

matrix:
  allow_failures:
    - julia: 0.6
    - julia: 0.7
    - julia: nightly

notifications:
    email: false
