name = "GigaSOM"
uuid = "a03a9c34-069e-5582-a11c-5c984cab887c"
authors = ["laurentheirendt <laurent.heirendt@uni.lu>"]
version = "0.0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]